channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - watermark
  - tqdm
  - joblib
  - tpot
  - pip:
    - twitter
    - googlemaps
